### ISSUE TITLE
Client is too old

### ISSUE THREAD

**Issue by ghost** [akezeke/spotyxbmc#21]
Hi,

I'im trying to use spotyxbmc alpha 015 for windows, but there's an issue with my two computers, first one is running windows vista ultimate 64 bits, second is running windows seven 32 bits.

I'm always having this error message : "Client is too old, library will need to be updated. Connect ?"

If i answer "Yes" the message reappear. If i answer "No" i can't use spotify integration on xbmc.

What can I do to make it work right ? If you need more

Thanks a lot,

PS : Sorry for my approximate english.

**Comment by ivankelly** [comment]
probably something to do with the spotify 0.4 release. Perhaps spotyxbmc should move to using the offical spotify library, especially since openspotify isn't going to be maintained now (according to the main developer). I tried the official spotify 2 weeks ago with spotyxbmc, and it worked mostly (and then crashed), so it's something thats very possible to do. This was on linux.

**Comment by akezeke** [comment]
Yes you are correct, I cant provide binaries with the official spotify lib due to license issues, but you can compile it yourself, if you take a look inside the function that receives the artistbrowse results you will probably find how to get rid of the crash as well.

**Comment by ivankelly** [comment]
ah, is the crash a known issue? The binaries never worked for me anyhow since I was on debian and there was different dependencies. Why can't you provide binaries with the official lib? I can't remember seeing anything related to that when I was looking at it.

**Comment by msaspence** [comment]
why is this issue closed with no resolution?
seems insane that spotify would release a library and then not let you use it?

**Comment by akezeke** [comment]
I can use it, but it violates the xbmc license, but you as an end user can compile it and use it. 

Since openspotifylib that I use is mimicking the functionality of the official spotify lib the same code works (almost), and openspotifylib is not updated to support the new 0.4 functionality I will stay with 0.3 until XBMC is done with the addon merge so I can create a new better addon using official spotify lib.

When that happens I will not violate the license since XBMC is not compiled with the lib, the addon is compiled as a shared library and XBMC is loading it at runtime.

**Comment by Kimuth** [comment]
You say you'll "stay with 0.3"
But then the compiled spotyxbmc is useless?
I have to build spotyxbmc myself? With API key and stuff?
(I'm using Ubuntu)
