### ISSUE TITLE
Unable to compile alpha 012 with the latest xbmc-svn

### ISSUE THREAD

**Issue by Kitof** [akezeke/spotyxbmc#8]
I fix manually the first error (an "if" before else is missing in CodecFactory.cpp line 145).

But there are too many errors after that (many "undefined reference to `g_spotifyInterface'")

**Comment by akezeke** [comment]
Yeah I see that error to, thats what happens when I´m in a hurry :), but "undefined reference to `g_spotifyInterface'" suggests that spotiterface.cpp is not built properly have you downloaded the source files and put them in the right directories (xbmc/xbmc)? And also check the makefiles i the same directory that it is set to build spotiterface.cpp, should off course have been done by the patch already.

**Comment by Kitof** [comment]
Ok, my mistake. It was my personnal installation script ;)
